[package]
name = "redox_syscall"
version = "0.4.1"
description = "A Rust library to access raw Redox system calls"
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/syscall"
documentation = "https://docs.rs/redox_syscall"
edition = "2018"

[lib]
name = "syscall"

[features]
rustc-dep-of-std = ["core", "bitflags/rustc-dep-of-std"]

[dependencies]
bitflags = "1.1.0"
core = { version = "1.0.0", optional = true, package = "rustc-std-workspace-core" }
